# Synthetic data for example calculation

In [6]:
set.seed(1234)

## Predators

In [19]:
predators.n <- 10
fa.n <- 3
predators <- gtools::rdirichlet(predators.n, alpha=rep(1, fa.n))*100
predators

[,1]     [,2]      [,3]
 [1,] 23.494162 58.96695 17.538890
 [2,] 17.498384 22.14347 60.358142
 [3,] 43.635588 20.22682 36.137591
 [4,]  2.404220 24.24190 73.353879
 [5,] 24.348613 29.79913 45.852256
 [6,]  2.468948 93.43507  4.095985
 [7,] 55.634781 23.95708 20.408136
 [8,] 22.861087 27.68168 49.457233
 [9,] 44.227158 54.79275  0.980093
[10,] 55.037544 16.16741 28.795043

## Prey

In [20]:
prey.n <- 4
prey <- gtools::rdirichlet(prey.n, alpha=rep(1, fa.n))
prey

[,1]       [,2]      [,3]
[1,] 0.42405626 0.04671568 0.5292281
[2,] 0.39795717 0.25406737 0.3479755
[3,] 0.02193891 0.31061746 0.6674436
[4,] 0.21106789 0.07032582 0.7186063

## Calibration Coefficients

In [21]:
cal <- matrix(rep(gtools::rdirichlet(1, alpha=rep(1, fa.n)), predators.n), fa.n, predators.n)
cal

[,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]
[1,] 0.2160530 0.2160530 0.2160530 0.2160530 0.2160530 0.2160530 0.2160530
[2,] 0.5404574 0.5404574 0.5404574 0.5404574 0.5404574 0.5404574 0.5404574
[3,] 0.2434896 0.2434896 0.2434896 0.2434896 0.2434896 0.2434896 0.2434896
          [,8]      [,9]     [,10]
[1,] 0.2160530 0.2160530 0.2160530
[2,] 0.5404574 0.5404574 0.5404574
[3,] 0.2434896 0.2434896 0.2434896

In [22]:
QFASA::p.QFASA(predators, prey, cal, dist.meas = 1)

$`Diet Estimates`
              [,1]         [,2]         [,3]         [,4]
 [1,] 2.484076e-09 9.999990e-01 1.020250e-06 1.084432e-11
 [2,] 1.885825e-01 9.332867e-03 1.797435e-01 6.223411e-01
 [3,] 6.846876e-01 3.153124e-01 2.479382e-11 8.706199e-09
 [4,] 6.402507e-09 1.667503e-10 6.986673e-01 3.013327e-01
 [5,] 3.330659e-01 3.231192e-01 1.372595e-01 2.065554e-01
 [6,] 1.733161e-09 4.166858e-01 5.833141e-01 7.336610e-09
 [7,] 3.484464e-01 6.515536e-01 1.081966e-10 1.149074e-08
 [8,] 3.327329e-01 2.251262e-01 1.597258e-01 2.824151e-01
 [9,] 9.995107e-07 9.999990e-01 2.031697e-09 1.795473e-10
[10,] 7.170092e-01 2.829908e-01 8.243760e-10 1.269792e-08

$`Additional Measures`
$`Additional Measures`[[1]]
$`Additional Measures`[[1]]$ModFAS
          [,1]      [,2]      [,3]
[1,] 0.3979568 0.2540674 0.3479758

$`Additional Measures`[[1]]$DistCont
           [,1]       [,2]       [,3]
[1,] 0.00134838 0.04807069 0.03350193

$`Additional Measures`[[1]]$PropDistCont
           [,1]      [,2]      [,3]
[1,] 0.01626102 0.5797167 0.4040222

$`Additional Measures`[[1]]$MinDist
[1] 0.08292099


$`Additional Measures`[[2]]
$`Additional Measures`[[2]]$ModFAS
          [,1]      [,2]      [,3]
[1,] 0.2189833 0.1107791 0.6702377

$`Additional Measures`[[2]]$DistCont
             [,1]         [,2]         [,3]
[1,] 9.207655e-17 7.184381e-17 4.156753e-18

$`Additional Measures`[[2]]$PropDistCont
          [,1]      [,2]       [,3]
[1,] 0.5478232 0.4274455 0.02473122

$`Additional Measures`[[2]]$MinDist
[1] 1.680771e-16


$`Additional Measures`[[3]]
$`Additional Measures`[[3]]$ModFAS
          [,1]      [,2]      [,3]
[1,] 0.4158269 0.1120962 0.4720769

$`Additional Measures`[[3]]$DistCont
           [,1]        [,2]       [,3]
[1,] 0.02362556 0.002334997 0.01875784

$`Additional Measures`[[3]]$PropDistCont
          [,1]       [,2]      [,3]
[1,] 0.5283186 0.05221557 0.4194659

$`Additional Measures`[[3]]$MinDist
[1] 0.0447184


$`Additional Measures`[[4]]
$`Additional Measures`[[4]]$ModFAS
           [,1]      [,2]      [,3]
[1,] 0.07892967 0.2382097 0.6828606

$`Additional Measures`[[4]]$DistCont
           [,1]      [,2]       [,3]
[1,] 0.04442425 0.0721417 0.03385523

$`Additional Measures`[[4]]$PropDistCont
          [,1]     [,2]      [,3]
[1,] 0.2953324 0.479598 0.2250696

$`Additional Measures`[[4]]$MinDist
[1] 0.1504212


$`Additional Measures`[[5]]
$`Additional Measures`[[5]]$ModFAS
          [,1]      [,2]      [,3]
[1,] 0.3164348 0.1548148 0.5287504

$`Additional Measures`[[5]]$DistCont
             [,1]         [,2]         [,3]
[1,] 1.772607e-16 1.419211e-16 1.484911e-17

$`Additional Measures`[[5]]$PropDistCont
          [,1]     [,2]      [,3]
[1,] 0.5306717 0.424874 0.0444543

$`Additional Measures`[[5]]$MinDist
[1] 3.340309e-16


$`Additional Measures`[[6]]
$`Additional Measures`[[6]]$ModFAS
          [,1]      [,2]      [,3]
[1,] 0.1786204 0.2870538 0.5343258

$`Additional Measures`[[6]]$DistCont
          [,1]      [,2]      [,3]
[1,] 0.1395194 0.6278731 0.8358105

$`Additional Measures`[[6]]$PropDistCont
           [,1]      [,2]      [,3]
[1,] 0.08702541 0.3916367 0.5213379

$`Additional Measures`[[6]]$MinDist
[1] 1.603203


$`Additional Measures`[[7]]
$`Additional Measures`[[7]]$ModFAS
          [,1]      [,2]      [,3]
[1,] 0.4070513 0.1818164 0.4111323

$`Additional Measures`[[7]]$DistCont
          [,1]       [,2]      [,3]
[1,] 0.1290136 0.03066582 0.1235391

$`Additional Measures`[[7]]$PropDistCont
          [,1]      [,2]      [,3]
[1,] 0.4555267 0.1082761 0.4361971

$`Additional Measures`[[7]]$MinDist
[1] 0.2832186


$`Additional Measures`[[8]]
$`Additional Measures`[[8]]$ModFAS
         [,1]      [,2]      [,3]
[1,] 0.293801 0.1422158 0.5639832

$`Additional Measures`[[8]]$DistCont
             [,1]         [,2]         [,3]
[1,] 9.705476e-17 2.171213e-16 8.340247e-20

$`Additional Measures`[[8]]$PropDistCont
          [,1]      [,2]         [,3]
[1,] 0.3088364 0.6908982 0.0002653937

$`Additional Measures`[[8]]$MinDis